### ISSUE TITLE
geoip2.exe build error

### ISSUE THREAD

**Issue by sgeto** [gvanem/wsock-trace#5]
Trying to build geoip2.exe using the the command `nmake -f Makefile.vc6 geoip2.exe` exits with the following error (I increased the warning level to 4 [-W4] just in case):

```
Microsoft (R) Program Maintenance Utility Version 14.00.23918.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        geoip.exe -g4 > geoip-gen4.c
        geoip.exe -g6 > geoip-gen6.c
        cl -nologo -I. -W4 -Zi -DWIN32 -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0600 -MD -Ot -Gs -DUSE_DEF_FILE -IC:\Users\Ali\projects\luajit-2.0/src -DUSE_LUA -D_CRT_SECURE_NO_WARNINGS -DTEST_GEOIP -DUSE_FWRITE -DUSE_GEOIP_GENERATED geoip.c common.c in_addr.c init.c getopt.c  -Fegeoip2.exe -link -nologo -map -debug -verbose -incremental:no -subsystem:console -machine:x86 ws2_32.lib ole32.lib > link.tmp
NMAKE : fatal error U1077: 'cl' : return code '0x2'
Stop.
```

I'm using the latest LUAjit from the their public git repository. I don't think that's the problem though.

**Comment by gvanem** [comment]
Did you notice the ` > link.tmp'`at the end? Look inside it for a clue.

**Comment by gvanem** [comment]
I think I got hit by the same issue; the `%WSOCK_TRACE_LEVEL%`  must be below 2.

**Comment by sgeto** [comment]
hmm let me try. Out of curiosity, what does this option do?

 -DUSE_GEOIP_GENERATED

**Comment by sgeto** [comment]
still nothing...
here is the content of link.tmp:

```
C:\Users\Ali\projects\wsock-trace\src>cat link.tmp
geoip.c
c:\users\ali\projects\wsock-trace\src\geoip-gen4.c(1): error C2143: syntax error: missing '{' before '->'
c:\users\ali\projects\wsock-trace\src\geoip-gen4.c(1): error C2059: syntax error: '->'
c:\users\ali\projects\wsock-trace\src\geoip-gen4.c(4): warning C4129: 'A': unrecognized character escape sequence
c:\users\ali\projects\wsock-trace\src\geoip-gen4.c(4): warning C4129: 'g': unrecognized character escape sequence
c:\users\ali\projects\wsock-trace\src\geoip-gen4.c(5): warning C4129: 'A': unrecognized character escape sequence
c:\users\ali\projects\wsock-trace\src\geoip-gen4.c(5): warning C4129: 'g': unrecognized character escape sequence
c:\users\ali\projects\wsock-trace\src\geoip-gen4.c(108666): error C2065: 'ipv4_gen_array': undeclared identifier
c:\users\ali\projects\wsock-trace\src\geoip-gen4.c(108666): error C2109: subscript requires array or pointer type
c:\users\ali\projects\wsock-trace\src\geoip-gen4.c(108666): error C2198: 'smartlist_new_fixed': too few arguments for call
c:\users\ali\projects\wsock-trace\src\geoip-gen6.c(1): error C2143: syntax error: missing '{' before '->'
c:\users\ali\projects\wsock-trace\src\geoip-gen6.c(1): error C2059: syntax error: '->'
c:\users\ali\projects\wsock-trace\src\geoip-gen6.c(4): warning C4129: 'A': unrecognized character escape sequence
c:\users\ali\projects\wsock-trace\src\geoip-gen6.c(4): warning C4129: 'g': unrecognized character escape sequence
c:\users\ali\projects\wsock-trace\src\geoip-gen6.c(5): warning C4129: 'A': unrecognized character escape sequence
c:\users\ali\projects\wsock-trace\src\geoip-gen6.c(5): warning C4129: 'g': unrecognized character escape sequence
c:\users\ali\projects\wsock-trace\src\geoip-gen6.c(63316): error C2065: 'ipv6_gen_array': undeclared identifier
c:\users\ali\projects\wsock-trace\src\geoip-gen6.c(63316): error C2109: subscript requires array or pointer type
c:\users\ali\projects\wsock-trace\src\geoip-gen6.c(63316): error C2198: 'smartlist_new_fixed': too few arguments for call
geoip.c(1753): warning C4996: 'isatty': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _isatty. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_io.h(489): note: see declaration of 'isatty'
common.c
in_addr.c
init.c
getopt.c
Generating Code...
```

**Comment by gvanem** [comment]
It should improve the speed for looking up an address->country.  But I'm not sure it's worth it.
See:
```
#if defined(USE_GEOIP_GENERATED)
  #include "geoip-gen4.c"
  #include "geoip-gen6.c"
#endif
```

The above files contains generated fixed arrays of addresses and are included for building `geoip2.exe` only.

**Comment by gvanem** [comment]
> c:\users\ali\projects\wsock-trace\src\geoip-gen4.c(1): error C2143: syntax error: missing '{' before '->'

The same issue I had. Apply the above patch or do `set WSOCK_TRACE_LEVEL=1`.

**Comment by sgeto** [comment]
can I revert the changes to the makefile back before applying the fix?

**Comment by gvanem** [comment]
No sure what *changes* you mean. Anyway, I've pushed the above change. Just do a `git pull`.

**Comment by sgeto** [comment]
I did. But still no luck. Is it working for you? link.tmp gives the same output

**Comment by gvanem** [comment]
Did you delete the `geoip-gen*.c` first?

**Comment by sgeto** [comment]
yes i did

**Comment by gvanem** [comment]
Ok. In your `~/wsock_trace` set this:
```
[core]
trace_level = 2
```

Or as I do can be more handy:
```
[core]
trace_level = %WSOCK_TRACE_LEVEL%
```
E.g. if you call `wsock_trace`  programs from `.bat`-files. Like `curl.bat`:
```
@setlocal
@set WSOCK_TRACE_LEVEL=0
@c:\net\cURL\src\curl.exe %*
```

**Comment by sgeto** [comment]
the tracelevel is set to 2 by default. 
I just went ahead and tried to build it again using a fresh git clone. But I am getting the same error.

**Comment by gvanem** [comment]
Then what does the start of `geoip-gen*.c` look like? Must be the `trace_level > 1`.

**Comment by sgeto** [comment]
geoip-gen4.c:

```
  opt->MajorLinkerVersion: 14, opt->MinorLinkerVersion: 0
  opt->MajorLinkerVersion: 14, opt->MinorLinkerVersion: 0
  opt->MajorLinkerVersion: 14, opt->MinorLinkerVersion: 0, wild_tstamp: 0
  Parsed 108646 IPv4 records from "C:\Users\Ali\geoip".
  Parsed 31648 IPv6 records from "C:\Users\Ali\geoip6".
  g_cfg.screen_width: 9999, g_cfg.screen_heigth: 0, g_cfg.stdout_redirected: 1
  g_cfg.trace_file_okay: 0, g_cfg.trace_file_device: 1
  CPU speed: 1.169 MHz

/*
 * This file was generated at Fri Nov 25 01:37:49 2016.
 * by the Makefile command: "geoip.exe -g4 > geoip-gen4.c"
 * DO NOT EDIT!
 */
```

**Comment by sgeto** [comment]
if these lines in `geoip-gen*.c` are treated as comments, the build suceeds: 
```
  opt->MajorLinkerVersion: 14, opt->MinorLinkerVersion: 0
  opt->MajorLinkerVersion: 14, opt->MinorLinkerVersion: 0
  opt->MajorLinkerVersion: 14, opt->MinorLinkerVersion: 0, wild_tstamp: 0
```

**Comment by gvanem** [comment]
But those trace-lines are printed at `trace_level >= 2`. E.g.
`TRACE (2, "CPU speed: %.3f MHz\n", (double)rc.QuadPart / 1E6);`

As I wrote earlier, the default `trace_level = 1` in `[core]` now. 
But I'm writing a patch to generate the `geoip-gen*.c` files using `geoip.exe -4g <file>` instead.

**Comment by gvanem** [comment]
> But I'm writing a patch to generate the geoip-gen*.c files using geoip.exe -4g <file> instead.

Now I've done that. Please try after another `git pull`.

**Comment by sgeto** [comment]
yes! works perfectly

**Comment by gvanem** [comment]
Close issue since this patch fixed it: https://github.com/gvanem/wsock-trace/commit/7dc07f195113fada9f8e57ba78b2d125524ecfb4
